name: Nightly

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  push:
    branches:
      - main

jobs:
  build:
      strategy:
        matrix:
          os: [macos-10.15, windows-2022, ubuntu-18.04]
      runs-on: ${{ matrix.os }}
      steps:
        - name: Check out Git repository
          uses: actions/checkout@v1

        - name: Install Node.js, NPM and Yarn
          uses: actions/setup-node@v3
          with:
            node-version: 14

        - name: Install global deps
          shell: bash
          run: |
            npm install -g cross-zip-cli
            npm install -g 7zip-bin

        - name: Patch node gyp on Windows
          if: ${{ runner.os == 'Windows' }}
          shell: powershell
          run: |
            npm install --global node-gyp@latest
            npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}

        - name: build app
          shell: bash
          run: |
            if [[ "$RUNNER_OS" == "Windows" ]]; then
              yarn && yarn gulp vscode-win32-x64-min && cross-zip ../VSCode-win32-x64 CodeTerminal-win32-x64.zip
            fi
            if [[ "$RUNNER_OS" == "macOS" ]]; then
              yarn && yarn gulp vscode-darwin-x64-min && $(npm config get prefix)/lib/node_modules/7zip-bin/mac/x64/7za a -r CodeTerminalNightly-macOS.7z ../VSCode-darwin-x64
            fi
            if [[ "$RUNNER_OS" == "Linux" ]]; then
              yarn && yarn gulp vscode-linux-x64-min && $(npm config get prefix)/lib/node_modules/7zip-bin/linux/x64/7za a -r CodeTerminalNightly-linux.7z ../VSCode-linux-x64
            fi
          env:
            GH_TOKEN: ${{ secrets.github_token }}A

        - name: upload app
          uses: actions/upload-artifact@v2
          with:
            name: CodeTerminalNightly-${{ runner.OS }}
            path: |
              *.zip
              *.tar.gz
